### ISSUE TITLE
I Can't open page, the error is java.net.SocketException: No such file or directory

### ISSUE THREAD

**Issue by lixin-wei** [80degreeswest/bfmgr#9]
I want to launch bfmgr in a local machine with one buildfarm server.

I downloaded bfmgr and ran it by the following scripts:

```
wget https://github.com/80degreeswest/bfmgr/releases/download/1.0.15/bfmgr-1.0.15.jar
sudo chmod 777 /var/log -R
sudo java -jar bfmgr-1.0.15.jar
```

Then I went to http://localhost, and saw the following error page:
![image](https://user-images.githubusercontent.com/19600697/138304078-6b7d9905-d06f-4c32-8e13-b386c8ce87fb.png)

And the error log is:
```
 30 [INFO ] 2021-10-21 22:57:38.855 [http-nio-80-exec-1] o.a.h.i.e.RetryExec - I/O exception (java.net.SocketException) caught when processing request to {}->unix://localhost:80: No such file or directory
 31 [INFO ] 2021-10-21 22:57:38.855 [http-nio-80-exec-1] o.a.h.i.e.RetryExec - Retrying request to {}->unix://localhost:80
 32 [ERROR] 2021-10-21 22:57:38.865 [http-nio-80-exec-1] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is javax.ws.rs.ProcessingException: java.net.SocketException: No such file or              directory] with root cause
 33 java.net.SocketException: No such file or directory
 34     at org.newsclub.net.unix.NativeUnixSocket.connect(Native Method)
 35     at org.newsclub.net.unix.AFUNIXSocketImpl.connect(AFUNIXSocketImpl.java:263)
 36     at org.newsclub.net.unix.AFUNIXSocket.connect(AFUNIXSocket.java:156)
 37     at com.github.dockerjava.jaxrs.ApacheUnixSocket.connect(ApacheUnixSocket.java:63)
 38     at com.github.dockerjava.jaxrs.UnixConnectionSocketFactory.connectSocket(UnixConnectionSocketFactory.java:75)
 39     at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
 40     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
 41     at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
 42     at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
 43     at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
 44     at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
 45     at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
 46     at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
 47     at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
 48     at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:478)
```

Full log:
[log.txt](https://github.com/80degreeswest/bfmgr/files/7390602/log.txt)

Could anyone help me?

**Comment by 80degreeswest** [comment]
Can you double check that you have docker running?

**Comment by lixin-wei** [comment]
> Can you double check that you have docker running?

I've no docker running. Why it needs docker?

**Comment by 80degreeswest** [comment]
When you are running it locally, the way it launches buildfarm is via docker containers.

**Comment by lixin-wei** [comment]
> When you are running it locally, the way it launches buildfarm is via docker containers.

I see, thx. I thought it is a tool managing an existing cluster. So I need to create the cluster using bfmgr.

Does it have the functionality to create workers in different machines? I've many machines.

**Comment by 80degreeswest** [comment]
> > When you are running it locally, the way it launches buildfarm is via docker containers.
> 
> I see, thx. I thought it is a tool managing an existing cluster. So I need to create the cluster using bfmgr.
> 
> Does it have the functionality to create workers in different machines? I've many machines.

Not currently via docker containers, but it's possible in the future. It does, however, support deploying to multiple machines on AWS infrastructure (see README file).

**Comment by lixin-wei** [comment]
> Not currently via docker containers, but it's possible in the future. It does, however, support deploying to multiple machines on AWS infrastructure (see README file).

I see, sadlly I'm not using AWS.

**Comment by lixin-wei** [comment]
Is there anyway to create a cluster using my own prue machines?

And don't use docker, just launch pure worker processes in my machine. 

I've already set up the environment well. I just want a UI to manage my cluster.

**Comment by 80degreeswest** [comment]
No, there isn't anything to do that at this time.

**Comment by lixin-wei** [comment]
I see. Thank you for your clarification.
